/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:5183f198-4496-4cf3-bd13-cea19db18900",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_YQJEs0F3d",
    "aws_user_pools_web_client_id": "659ddef1b795u23t6r0tj9krr2",
    "oauth": {}
};


export default awsmobile;
